name: Azure VPS Deploy

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}   
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "Build number is $BUILD_NUMBER"
      - run: yarn install
      - run: cp ~/battle-rode-be/.env ./.env
      - run: pm2 start ecosystem.dev.config.json
      - run: pm2 start app
      - run: pm2 save
      - run: echo GIT_VERSION=$BATTLE_RODE_VERSION>>./.env
      - run: export BATTLE_RODE_VERSION=$(($BATTLE_RODE_VERSION+1))
