name: Production Deploy

on: [push]

jobs:
  build:
    runs-on: production

    steps:
      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}   
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: yarn install
      - run: cp ~/rode.env ./.env
      - run: pm2 start ecosystem.dev.config.json
      - run: pm2 start rode-battle
      - run: pm2 save
      - run: echo -en '\n'>>./.env
      - run: echo $GIT_ACTION>>./.env
      - run: echo GIT_ACTION_VERSION=`echo $(($BUILD_NUMBER+40+100)) | fold -w1 | paste -sd.`>>./.env

