name: Production

on: [push]

jobs:
  build:
    runs-on: production

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}   
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: yarn install
      - run: cp ~/rode.env ./.env
      - run: pm2 start ecosystem.config.json
      - run: pm2 start rode-battle
      - run: pm2 save
