name: Production Deploy

on: [push]

jobs:
  build:
    runs-on: production

    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: yarn install
      - run: cp ~/rode.env ./.env
      - run: cp ~/cert ./cert
      - run: pm2 start ecosystem.dev.config.json
      - run: pm2 start rode-battle
      - run: pm2 save

